proyecto2/docker/rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :libros
  get 'welcome/index'
  root 'welcome#index'
  get '/libros', to: 'libros_controller#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

proyecto2/docker/rails/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

proyecto2/docker/rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

proyecto2/docker/rails/app/models/libro.rb
class Libro < ApplicationRecord
end

proyecto2/docker/rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

proyecto2/docker/rails/app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  # GET /libros
  # GET /libros.json
  def index

    @libros = Libro.all

  end

  # GET /libros/1
  # GET /libros/1.json
  def show
  end

  # GET /libros/new
  def new

    @libro = Libro.new
    
    
  end

  # GET /libros/1/edit
  def edit


  end

  # POST /libros
  # POST /libros.json
  def create

    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
    
    
  end

  # PATCH/PUT /libros/1
  # PATCH/PUT /libros/1.json
  def update

    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
    
    
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy

    @libro.destroy
    respond_to do |format|
      format.html { redirect_to libros_url, notice: 'Libro was successfully destroyed.' }
      format.json { head :no_content }
    end

    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libro_params
      params.require(:libro).permit(:titulo, :autor, :fecha_pub, :cod_dewey)
    end
  end

proyecto2/docker/rails/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		 @libros = Libro.all
	end
end

proyecto2/docker/rails/app/helpers/application_helper.rb
module ApplicationHelper
end

proyecto2/docker/rails/app/helpers/libros_helper.rb
module LibrosHelper
end

proyecto2/docker/rails/app/helpers/welcome_helper.rb
module WelcomeHelper
end

proyecto2/docker/rails/app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Login", new_session_path(resource_name) %><br />
<% end -%>

<!-- <%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%> -->

proyecto2/docker/rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

proyecto2/docker/rails/app/views/libros/_form.html.erb
<%= form_for(libro) do |f| %>
<% if libro.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

  <ul>
    <% libro.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :titulo %>
  <%= f.text_field :titulo %>
</div>

<div class="field">
  <%= f.label :autor %>
  <%= f.text_field :autor %>
</div>

<div class="field">
  <%= f.label :fecha_pub %>
  <%= f.number_field :fecha_pub %>
</div>

<div class="field">
  <%= f.label :cod_dewey %>
  <%= f.text_field :cod_dewey %>
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

proyecto2/docker/rails/app/views/libros/edit.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Editar Libro</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <ul class="nav navbar-nav navbar-right">
          <button type="button" class="btn btn-default navbar-btn"><%= link_to 'Back', libros_path %>
          </button>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<div class="row container">
  <div class="col-md-6 col-md-offset-1">
<%= render 'form', libro: @libro %>
<%= link_to 'Show', @libro %>
</div>
</div>
<!-- <%= link_to 'Back', libros_path %> -->

proyecto2/docker/rails/app/views/libros/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Libros</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <button type="button" class="btn btn-default navbar-btn"><%= link_to 'Nuevo Libro', new_libro_path, :method => :get %>
        </button>

        <% if admin_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <button type="button" class="btn btn-default navbar-btn"><%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>
          </button>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="row container">
    <div class="col-md-6 col-md-offset-3">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Titulo</th>
            <th>Autor</th>
            <th>Fecha pub</th>
            <th>Cod dewey</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <table>
        </div>
      </div>

      <div class="row container">
        <div class="col-md-6 col-md-offset-3">
          <table class="table table-striped">
            <tbody>
              <% @libros.each do |libro| %>
              <tr>
                <td><%= libro.titulo %></td>
                <td><%= libro.autor %></td>
                <td><%= libro.fecha_pub %></td>
                <td><%= libro.cod_dewey %></td>
                <td><%= link_to 'Show', libro %></td>
                <td><%= link_to 'Edit', edit_libro_path(libro) %></td>
                <td><%= link_to 'Destroy', libro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <br>
      <!-- <%= link_to 'New Libro', new_libro_path %> -->

proyecto2/docker/rails/app/views/libros/new.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Nuevo Libro</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <ul class="nav navbar-nav navbar-right">
          <button type="button" class="btn btn-default navbar-btn"><%= link_to 'Back', libros_path %>
          </button>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="row container">
  <div class="col-md-6 col-md-offset-1">
      <%= render 'form', libro: @libro %>
  </div>
</div>

proyecto2/docker/rails/app/views/libros/show.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Informacion Libro</a>
    </div>

<ul class="nav navbar-nav navbar-right">
  <button type="button" class="btn btn-default navbar-btn"><%= link_to 'Back', libros_path %>
</button>

  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

<div class="row container">
  <div class="col-md-6 col-md-offset-5">
    <table class="table table-striped">
      <p>
        <strong>Titulo:</strong>
        <%= @libro.titulo %>
      </p>

      <p>
        <strong>Autor:</strong>
        <%= @libro.autor %>
      </p>

      <p>
        <strong>Fecha pub:</strong>
        <%= @libro.fecha_pub %>
      </p>

      <p>
        <strong>Cod dewey:</strong>
        <%= @libro.cod_dewey %>
      </p>
      <table>
      </div>
    </div>

<%= link_to 'Edit', edit_libro_path(@libro) %> 
<!-- <%= link_to 'Back', libros_path %> -->

proyecto2/docker/rails/app/views/welcome/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">SoftLog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <button type="button" class="btn btn-default navbar-btn"><%= link_to "Admin", '/libros', :method => :get %>
</button>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="row container">
	<div class="col-md-6 col-md-offset-4">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Titulo</th>
					<th>Autor</th>
					<th>Fecha pub</th>
					<th>Cod dewey</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @libros.each do |libro| %>
				<tr>
					<td><%= libro.titulo %></td>
					<td><%= libro.autor %></td>
					<td><%= libro.fecha_pub %></td>
					<td><%= libro.cod_dewey %></td>
				</tr>
				<% end %>
			</tbody>
		</table>


	</div>
</div>